### ISSUE TITLE
Server boot failed - UnsupportedOperationException: WFLYCTL0309

### ISSUE THREAD

**Issue by plutext** [jboss-dockerfiles/modeshape#2]
```
[fedora@ip-172-30-0-128 ~]$ sudo docker run -it jboss/modeshape
=========================================================================

  JBoss Bootstrap Environment

  JBOSS_HOME: /opt/jboss/wildfly

  JAVA: /usr/lib/jvm/java/bin/java

  JAVA_OPTS:  -server -XX:+UseCompressedOops  -server -XX:+UseCompressedOops -Xms64m -Xmx512m -XX:MaxPermSize=256m -Djava.net.preferIPv4Stack=true -Djboss.modules.system.pkgs=org.jboss.byteman -Djava.awt.headless=true

=========================================================================

OpenJDK 64-Bit Server VM warning: ignoring option MaxPermSize=256m; support was removed in 8.0
03:44:43,461 INFO  [org.jboss.modules] (main) JBoss Modules version 1.4.3.Final
03:44:43,909 INFO  [org.jboss.msc] (main) JBoss MSC version 1.2.6.Final
03:44:44,013 INFO  [org.jboss.as] (MSC service thread 1-2) WFLYSRV0049: WildFly Full 9.0.1.Final (WildFly Core 1.0.1.Final) starting
03:44:45,106 ERROR [org.jboss.as.server] (Controller Boot Thread) WFLYSRV0055: Caught exception during boot: org.jboss.as.controller.persistence.ConfigurationPersistenceException: WFLYCTL0085: Failed to parse configuration
        at org.jboss.as.controller.persistence.XmlConfigurationPersister.load(XmlConfigurationPersister.java:131) [wildfly-controller-1.0.1.Final.jar:1.0.1.Final]
        at org.jboss.as.server.ServerService.boot(ServerService.java:350) [wildfly-server-1.0.1.Final.jar:1.0.1.Final]
        at org.jboss.as.controller.AbstractControllerService$1.run(AbstractControllerService.java:271) [wildfly-controller-1.0.1.Final.jar:1.0.1.Final]
        at java.lang.Thread.run(Thread.java:745) [rt.jar:1.8.0_51]
Caused by: javax.xml.stream.XMLStreamException: WFLYCTL0083: Failed to load module org.jboss.as.threads
        at org.jboss.as.controller.parsing.ExtensionXml.parseExtensions(ExtensionXml.java:155) [wildfly-controller-1.0.1.Final.jar:1.0.1.Final]
        at org.jboss.as.server.parsing.StandaloneXml.readServerElement_1_4(StandaloneXml.java:433) [wildfly-server-1.0.1.Final.jar:1.0.1.Final]
        at org.jboss.as.server.parsing.StandaloneXml.readElement(StandaloneXml.java:144) [wildfly-server-1.0.1.Final.jar:1.0.1.Final]
        at org.jboss.as.server.parsing.StandaloneXml.readElement(StandaloneXml.java:106) [wildfly-server-1.0.1.Final.jar:1.0.1.Final]
        at org.jboss.staxmapper.XMLMapperImpl.processNested(XMLMapperImpl.java:110) [staxmapper-1.2.0.Final.jar:1.2.0.Final]
        at org.jboss.staxmapper.XMLMapperImpl.parseDocument(XMLMapperImpl.java:69) [staxmapper-1.2.0.Final.jar:1.2.0.Final]
        at org.jboss.as.controller.persistence.XmlConfigurationPersister.load(XmlConfigurationPersister.java:123) [wildfly-controller-1.0.1.Final.jar:1.0.1.Final]
        ... 3 more
Caused by: java.util.concurrent.ExecutionException: java.lang.UnsupportedOperationException: WFLYCTL0309: Legacy extension 'org.jboss.as.threads' is not supported on servers running this version. The extension is only supported for use by hosts running a previous release in a mixed-version managed domain
        at java.util.concurrent.FutureTask.report(FutureTask.java:122) [rt.jar:1.8.0_51]
        at java.util.concurrent.FutureTask.get(FutureTask.java:192) [rt.jar:1.8.0_51]
        at org.jboss.as.controller.parsing.ExtensionXml.parseExtensions(ExtensionXml.java:147) [wildfly-controller-1.0.1.Final.jar:1.0.1.Final]
        ... 9 more
Caused by: java.lang.UnsupportedOperationException: WFLYCTL0309: Legacy extension 'org.jboss.as.threads' is not supported on servers running this version. The extension is only supported for use by hosts running a previous release in a mixed-version managed domain
        at org.jboss.as.controller.extension.AbstractLegacyExtension.initializeParsers(AbstractLegacyExtension.java:81) [wildfly-controller-1.0.1.Final.jar:1.0.1.Final]
        at org.jboss.as.controller.parsing.ExtensionXml.loadModule(ExtensionXml.java:183) [wildfly-controller-1.0.1.Final.jar:1.0.1.Final]
        at org.jboss.as.controller.parsing.ExtensionXml.access$000(ExtensionXml.java:69) [wildfly-controller-1.0.1.Final.jar:1.0.1.Final]
        at org.jboss.as.controller.parsing.ExtensionXml$1.call(ExtensionXml.java:127) [wildfly-controller-1.0.1.Final.jar:1.0.1.Final]
        at org.jboss.as.controller.parsing.ExtensionXml$1.call(ExtensionXml.java:124) [wildfly-controller-1.0.1.Final.jar:1.0.1.Final]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [rt.jar:1.8.0_51]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [rt.jar:1.8.0_51]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [rt.jar:1.8.0_51]
        at java.lang.Thread.run(Thread.java:745) [rt.jar:1.8.0_51]
        at org.jboss.threads.JBossThread.run(JBossThread.java:320) [jboss-threads-2.2.0.Final.jar:2.2.0.Final]

03:44:45,114 FATAL [org.jboss.as.server] (Controller Boot Thread) WFLYSRV0056: Server boot has failed in an unrecoverable manner; exiting. See previous messages for details.
03:44:45,132 INFO  [org.jboss.as.server] (Thread-2) WFLYSRV0220: Server shutdown has been requested.
03:44:45,164 INFO  [org.jboss.as] (MSC service thread 1-2) WFLYSRV0050: WildFly Full 9.0.1.Final (WildFly Core 1.0.1.Final) stopped in 17ms
```

**Comment by plutext** [comment]
https://github.com/jboss-dockerfiles/modeshape/commit/a0bd1e29ec5a2ed182f614d145a9be3c3aae097f bumps modeshape from 4.0.0 to 4.3.0

An image built from that Dockerfile works (ie WildFly 9.0.1 starts without error).

**Comment by plutext** [comment]
Spoke to soon :-(

 bin/standalone.sh -c standalone-modeshape.xml

```
10:18:03,187 INFO  [org.jboss.modules] (main) JBoss Modules version 1.4.3.Final
10:18:03,383 INFO  [org.jboss.msc] (main) JBoss MSC version 1.2.6.Final
10:18:03,460 INFO  [org.jboss.as] (MSC service thread 1-4) WFLYSRV0049: WildFly Full 9.0.1.Final (WildFly Core 1.0.1.Final) starting
10:18:04,112 ERROR [org.jboss.as.server] (Controller Boot Thread) WFLYSRV0055: Caught exception during boot: org.jboss.as.controller.persistence.ConfigurationPersistenceException: WFLYCTL0085: Failed to parse configuration
        at org.jboss.as.controller.persistence.XmlConfigurationPersister.load(XmlConfigurationPersister.java:131)
        at org.jboss.as.server.ServerService.boot(ServerService.java:350)
        at org.jboss.as.controller.AbstractControllerService$1.run(AbstractControllerService.java:271)
        at java.lang.Thread.run(Thread.java:745)
Caused by: javax.xml.stream.XMLStreamException: WFLYCTL0083: Failed to load module org.jboss.as.threads
        at org.jboss.as.controller.parsing.ExtensionXml.parseExtensions(ExtensionXml.java:155)
        at org.jboss.as.server.parsing.StandaloneXml.readServerElement_1_4(StandaloneXml.java:433)
        at org.jboss.as.server.parsing.StandaloneXml.readElement(StandaloneXml.java:144)
        at org.jboss.as.server.parsing.StandaloneXml.readElement(StandaloneXml.java:106)
        at org.jboss.staxmapper.XMLMapperImpl.processNested(XMLMapperImpl.java:110)
        at org.jboss.staxmapper.XMLMapperImpl.parseDocument(XMLMapperImpl.java:69)
        at org.jboss.as.controller.persistence.XmlConfigurationPersister.load(XmlConfigurationPersister.java:123)
        ... 3 more
Caused by: java.util.concurrent.ExecutionException: java.lang.UnsupportedOperationException: WFLYCTL0309: Legacy extension 'org.jboss.as.threads' is not supported on servers running this version. The extension is only supported for use by hosts running a previous release in a mixed-version managed domain
        at java.util.concurrent.FutureTask.report(FutureTask.java:122)
        at java.util.concurrent.FutureTask.get(FutureTask.java:192)
        at org.jboss.as.controller.parsing.ExtensionXml.parseExtensions(ExtensionXml.java:147)
        ... 9 more
```

**Comment by plutext** [comment]
**FROM jboss/wildfly:latest** pulls in WildFly 9.0.1.Final (at the time of writing).

The problem is that Modeshape 4.x isn’t compatible with that!

Until Modeshape 4.4 is released (which apparently will work with WildFly 9x), the easiest solution is to use WildFly 8:

So change the Dockerfile so it says **FROM jboss/wildfly:8.2.1.Final**

A couple of other tips:- since you’ll want to try the webapps from outside the container, also add to your Dockerfile

```
EXPOSE 8080
```

and once the container is running, edit standalone/configuration/standalone-modeshape.xml  with something like 

```
    <interface name="public">
        <any-address/>
    </interface>
```
